include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules:
    provider_parameters: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    depend_on_referenced_packages: false
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true