name: finance
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  firebase_ui_auth: ^1.1.5
  go_router: ^6.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.3.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/png/
