name: finance
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  http: 1.2.1
  flutter_bloc: 8.1.6
  go_router: 14.1.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  intl: 0.19.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  equatable: ^2.0.5
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  mockito: 5.4.4
  build_runner: 2.4.11
  flutter_gen_runner: ^5.1.0+1
  freezed: 2.5.2
  json_serializable: 6.8.0
flutter_gen:
  parse_metadata: true
  integrations:
    flutter_svg: true
    rive: true
  assets:
    output:
      directory_path_enabled: true
flutter:
  uses-material-design: true
  assets:
    - assets/png/
